### ISSUE TITLE
Reporting to the Legal Authorities

### ISSUE THREAD

**Issue by afs2015** [ADubhlaoich/dance-code-of-conduct#6]
I'm unfamiliar with law in Ireland, but to my understanding for most businesses in the United States if someone reports a crime it can be considered negligent to not bring that to the attention of the police.

Should the section that mentions 'Reported to the legal authorities' as an option of action include a disclaimer along the lines of *we are required to bring to the attention of the police any crimes committed on our premises?

**Comment by ADubhlaoich** [comment]
I'm unsure if it's considered negligent or not, actually - I'll have to look into it. I think it's a given either way, but best to remove as much ambiguity as possible.

**Comment by ADubhlaoich** [comment]
There's now a small mention in the opening section of the document that people should talk to their local authorities about whether or not they're legally obliged to report crimes - as it turns out, it's not the case for a venue or event organiser in Ireland, and is in fact the responsibility of the victim of a crime.
